version: "3"
services:
  odoo:
    build:
      context: .
    container_name: ${PROJECT_NAME}
    command: odoo -u pos_ingeint --dev=all
    depends_on:
      - pos_db
    ports:
      - ${ODOO_PORT}:8069
    volumes:
      - odoo-web-pos:/var/lib/odoo
      - ./config:/etc/odoo
      # - ./enterprise:/mnt/extra-addons
      - ./custom:/mnt/custom-addons
    environment:
      - PYTHONUNBUFFERED=0
    # restart: always
    networks:
      - postgres_bd
  db:
    container_name: ${PROJECT_NAME}_db
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-pos:/var/lib/postgresql/data/pgdata
    # restart: always
    networks:
      - postgres_bd
  pgadmin:
    container_name: ${PROJECT_NAME}_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: jdap.dmc@gmail.com
      PGADMIN_DEFAULT_PASSWORD: odoo
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    networks:
      - postgres_bd
    volumes:
        - pgadmin:/root/.pgadmin

    ports:
      - ${PGADMIN_PORT}:80    
    # restart: unless-stopped

networks:
  postgres_bd:

volumes:
  odoo-web-pos:
  odoo-db-pos:
  pgadmin: