version: "3"
services:
  web-hagus:
    build:
      context: .
    container_name: pos
    # command: odoo --dev=all -u binaural_webpos
    depends_on:
      - pos_db
    ports:
      - "16000:8069"
    volumes:
      - odoo-web-hagus:/var/lib/odoo
      - ./config:/etc/odoo
      # - ./enterprise:/mnt/extra-addons
      - ./custom:/mnt/custom-addons
    environment:
      - PYTHONUNBUFFERED=0
    # restart: always
    networks:
      - postgres_bd
  pos_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-hagus:/var/lib/postgresql/data/pgdata
    # restart: always
    networks:
      - postgres_bd
  pgadmin:
    container_name: pos_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: jdap.dmc@gmail.com
      PGADMIN_DEFAULT_PASSWORD: odoo
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    networks:
      - postgres_bd
    volumes:
        - pgadmin:/root/.pgadmin

    ports:
      - "80:80"    
    # restart: unless-stopped

networks:
  postgres_bd:

volumes:
  odoo-web-hagus:
  odoo-db-hagus:
  pgadmin: